let g:custom_config_dir = '$HOME/.config/nvim/custom/'
execute 'source ' . g:custom_config_dir . 'common.vim'
execute 'source ' . g:custom_config_dir . 'plug.vim'
execute 'source ' . g:custom_config_dir . 'theme.vim'
execute 'source ' . g:custom_config_dir . 'coc.vim'
execute 'source ' . g:custom_config_dir . 'defx.vim'
execute 'source ' . g:custom_config_dir . 'lightline.vim'
execute 'source ' . g:custom_config_dir . 'vista.vim'
execute 'source ' . g:custom_config_dir . 'vimspector.vim'
